from unittest import TestCase
import cards

class TestGetSuit(TestCase):
    def test_getSuit(self):
        expectedResults = []
        expectedResults.append(0)
        expectedResults.append(1)
        expectedResults.append(2)
        expectedResults.append(3)
        expectedResults.append(0)
        expectedResults.append(1)
        expectedResults.append(2)
        expectedResults.append(3)
        expectedResults.append(0)
        expectedResults.append(1)
        expectedResults.append(2)
        expectedResults.append(3)
        expectedResults.append(0)
        expectedResults.append(1)
        expectedResults.append(2)
        expectedResults.append(3)
        expectedResults.append(0)
        expectedResults.append(1)
        expectedResults.append(2)
        expectedResults.append(3)
        expectedResults.append(0)
        expectedResults.append(1)
        expectedResults.append(2)
        expectedResults.append(3)
        expectedResults.append(0)
        expectedResults.append(1)
        expectedResults.append(2)
        expectedResults.append(3)
        expectedResults.append(0)
        expectedResults.append(1)
        expectedResults.append(2)
        expectedResults.append(3)
        expectedResults.append(0)
        expectedResults.append(1)
        expectedResults.append(2)
        expectedResults.append(3)
        expectedResults.append(0)
        expectedResults.append(1)
        expectedResults.append(2)
        expectedResults.append(3)
        expectedResults.append(0)
        expectedResults.append(1)
        expectedResults.append(2)
        expectedResults.append(3)
        expectedResults.append(0)
        expectedResults.append(1)
        expectedResults.append(2)
        expectedResults.append(3)
        expectedResults.append(0)
        expectedResults.append(1)
        expectedResults.append(2)
        expectedResults.append(3)

        for i in 0,len(expectedResults)-1:
            self.assertEquals(cards.getSuit(i),expectedResults[i])