from unittest import TestCase
import cards

class TestGetSingleCardDescription(TestCase):
    def test_getSingleCardDescription(self):
        
        expectedResults = []
        expectedResults.append("Two")
        expectedResults.append("Two")
        expectedResults.append("Two")
        expectedResults.append("Two")
        expectedResults.append("Three")
        expectedResults.append("Three")
        expectedResults.append("Three")
        expectedResults.append("Three")
        expectedResults.append("Four")
        expectedResults.append("Four")
        expectedResults.append("Four")
        expectedResults.append("Four")
        expectedResults.append("Five")
        expectedResults.append("Five")
        expectedResults.append("Five")
        expectedResults.append("Five")
        expectedResults.append("Six")
        expectedResults.append("Six")
        expectedResults.append("Six")
        expectedResults.append("Six")
        expectedResults.append("Seven")
        expectedResults.append("Seven")
        expectedResults.append("Seven")
        expectedResults.append("Seven")
        expectedResults.append("Eight")
        expectedResults.append("Eight")
        expectedResults.append("Eight")
        expectedResults.append("Eight")
        expectedResults.append("Nine")
        expectedResults.append("Nine")
        expectedResults.append("Nine")
        expectedResults.append("Nine")
        expectedResults.append("Ten")
        expectedResults.append("Ten")
        expectedResults.append("Ten")
        expectedResults.append("Ten")
        expectedResults.append("Jack")
        expectedResults.append("Jack")
        expectedResults.append("Jack")
        expectedResults.append("Jack")
        expectedResults.append("Queen")
        expectedResults.append("Queen")
        expectedResults.append("Queen")
        expectedResults.append("Queen")
        expectedResults.append("King")
        expectedResults.append("King")
        expectedResults.append("King")
        expectedResults.append("King")
        expectedResults.append("Ace")
        expectedResults.append("Ace")
        expectedResults.append("Ace")
        expectedResults.append("Ace")

        for i in 0,len(expectedResults)-1:
            self.assertEquals(cards.getSingleCardDescription(i),expectedResults[i])
